### ISSUE TITLE
Galaxy Fight (Neo Geo CD) is missing some sound effects

### ISSUE THREAD

**Issue by Silanda** [barry65536/FBAlpha#12]
As per the title, some sound effects don't seem to play. Oddly, most do; the round announcer, menu sound effects, and sampled hit sound effects all play. What's missing are the character speech samples. Taunting speech, special move vocals, etc, are all missing.

This was tested with a disc I ripped, on a self compiled version from current source as well as the official 0.2.97.43 release. The behaviour is the same on both.

**Comment by dinkc64** [comment]
Hi,
I'm no expert with neo-geo cd, so bear with me..
Do you know of another emulator that plays this game fine?  I really need something to compare to - other than yt videos.
I tried raine32, but it crashes before the round starts.
Also did you try with any of the "publicly available" rips?

best regards,
- dink

**Comment by Silanda** [comment]
Thanks!

FWIW, it runs 99% on MAME. 99% as I'm not sure all sounds are working during the boss fight (Felden).

**Comment by dinkc64** [comment]
Good news, I have a fix - but I won't be able to check it in until tonight (around 9pm Detroit time).
Unfortunately I have to leave for the day and I'm already late.

**Comment by dinkc64** [comment]
Thanks for the bug report! :)
The fix is in - please test it and let me know how it goes.

best regards,
- dink

**Comment by Silanda** [comment]
Awesome! I've only had a quick play, but not only has this fixed Galaxy Fight, it seems to have fixed the audio in Real Bout Fatal Fury, the sound effects in Fatal Fury 3, and a minor sound issue in King of Fighters 97.

I'll have a more thorough play tomorrow, but this fix looks great!

Thanks!

**Comment by dinkc64** [comment]
awesome, that's great news!  That makes it worth it, because this fix took me 6+ hours of debugging/trying different things. 

best regards,
- dink

**Comment by Silanda** [comment]
I've done a complete play through of Galaxy Fight and KoF '97. They both seem fine. 

The only thing I noticed was that the stage background music doesn't stop when the game returns to the rotating planet screen after you win a fight. I believe it's supposed to, although I don't have a working NeoCD to check against at the moment, only MAME and Youtube longplays. That's unrelated to this fix anyway.

**Comment by dinkc64** [comment]
The latest commit should take care of the cd audio stopping issue.  :)

**Comment by dinkc64** [comment]
Can you please tell me which games do this, and what part do they do it at?  

best regards,
- dink

**Comment by Silanda** [comment]
I tested Real Bout and KoF '96, and the music didn't resume after being unpaused.

As the CD playback pause/resume routine checks that CDEmuStatus is set to playing before resuming playback, I figured that the status would have to be changed back from paused to playing or the check would have to be removed. Changing the status seemed safer.
