### ISSUE TITLE
Real Bout Fatal Fury (Neo Geo CD): No audio if dipswitch region set to anything but default (Europe)

### ISSUE THREAD

**Issue by Silanda** [barry65536/FBAlpha#13]
Another Neo Geo CD bug I'm afraid. 

This one's not serious, as the game's perfectly playable now as long as you don't change the region, but odd. The recent fix fixed the sound effects that were missing from this game, but there's no audio at all if you set the region to anything other than the default of Europe. No FM, no CDDA, no samples, nothing.

I ripped the game myself and it's a Japanese copy.

**Comment by dinkc64** [comment]
My version of Real Bout Fatal Fury (jp/us) works fine with any region.  How are you changing your region?  also, can you try deleting config/games/neocdz.fs to see if that helps?
Another question, I would like to try your rip on my side if you don't mind, can you pm me on the official fba forums?  My name is dink there / http://neo-source.com/

**Comment by Silanda** [comment]
The results I'm having are best described as odd: the problem is intermittent and probably not what I originally thought. 

I tried deleting neocdz.fs and initially I thought it had fixed things. Then I loaded the game again, and the sound was gone again, Upon resetting, the sound came back. I then set the dipswitch to Europe and reset and the sound was gone again, only to return upon another reset.

I'm seeing three states when the game's loaded or reset: sound works fine, sound works but crackles (at least initially), no sound at all.

I'll be out most of the day (UK time), but I'll try to contact you on the forum later.

**Comment by dinkc64** [comment]
Hi,
I managed to fix the problem - please give the latest a try :)   The bug was being elusive, but this morning when I booted real bout, it started without any sound.  This was enough for me to figure out what was going on.
Thanks for the excellent bug reports!  You may skip the forum step if you'd like.

best regards,
- dink

**Comment by Silanda** [comment]
Thanks again. The new build works fine!

**Comment by Silanda** [comment]
Bad news. The fix for Real Bout seems to break the audio in King of Fighters '97. Same symptoms as Real Bout (no audio at all) except it's not intermittent.

**Comment by dinkc64** [comment]
problem with kof97-cd is fixed :)  thanks again for the excellent bug finds!

best regards,
- dink

**Comment by Silanda** [comment]
Thanks again!
