### ISSUE TITLE
No HDD data was found.

### ISSUE THREAD

**Issue by LodanZark** [barry65536/FBAlpha#14]
Killer Instinct (and 2) does not work, I assume that requires CHD file, since I haven't seen any folder designated to the chd files in fba directory, I added the chd  files into Roms folder, yet I got same error
(FBAlpha normal build)
![image](https://user-images.githubusercontent.com/11250310/52319725-2e14fe00-29c3-11e9-8191-2fd2dfe8ec79.png)

**Comment by dinkc64** [comment]
Misc -> configure support file paths :)
see forum, chd needs to be in uncompressed state to work:
http://neo-source.com/index.php?topic=2666.msg26320

**Comment by LodanZark** [comment]
It work ;) thank you very much.

**Comment by dinkc64** [comment]
You're welcome :)
