### ISSUE TITLE
Last Resort (Neo Geo CD) missing SFX

### ISSUE THREAD

**Issue by ArcadeTV** [barry65536/FBAlpha#18]
Found in Version: FB Alpha 0.2.97.43
Tested with: Last Resort 
-Tosec ISO
-SuperDAT ISO
-MAME CHD to CD image conversion

The game runs normally but 99% of all SFX are muted or not present. The only noticable SFX is when the drone docks onto the ship.

**Comment by barbudreadmon** [comment]
You'll have to update to latest nightlies for more proper ngcd emulation, i think you can get them from http://ashura.mameworld.info/nightlybuilds/fba_builds.html

**Comment by ArcadeTV** [comment]
I just found dink is working hard since a couple of weeks...
http://neo-source.com/index.php?topic=2487.msg26471#msg26471

I'll test again with a recent version, sorry to bother!

**Comment by ArcadeTV** [comment]
In the latest commit (10 hrs ago) everthing is just wonderful. Thanks for the hint to CDmage and THANK YOU for putting so much efforts into the ngcd! This is so much appreciated!
