### ISSUE TITLE
UI language problem...

### ISSUE THREAD

**Issue by dsno1** [barry65536/FBAlpha#20]
I have a problem with using UI language in the following order. (x86, x64 same problem)

"Export UI translation template..." and imported file template.flt

======

Language file E:\FBA\config\localisation\template.flt is malformed.
Please remove or repair the file.

Parse error at line 479.
Problem:	rogue closing bracket.

======

Commit Used : 4fc1898dcae7cb9585dfb44433971982b573d513
Compiled : vc2013

**Comment by dinkc64** [comment]
@barry65536 any ideas?  I tried to figure out what is wrong here, but I'm at a loss..
