### ISSUE TITLE
[CDZ] Couldn't initialize CD emulation. error

### ISSUE THREAD

**Issue by LodanZark** [barry65536/FBAlpha#23]
I've put the validated neogeo.zip and neocdz.zip into rom folder, rescan it to make sure it's working properly, then pressed the Ctrl+Shift+F6 (Start Neo Geo CDz...) and I got the following error:
![error](https://user-images.githubusercontent.com/11250310/53698136-85469c80-3dd0-11e9-9bf8-04b6e461c869.png)

**Comment by dinkc64** [comment]
Start Neo CDZ basically starts cdz emulation with the last game you had selected.  If you get that error you'll need to either select the .cue file of a cdz game with "Select CD Image (CUE/CCD)" first, or set up the nice game selector with "Load Neo Geo CDZ Game".   With the latter option, you'll need to set up the directory to where your neogeo cdz images are located then hit scan, you'll be presented with a nice ui from which you can select the game:
![neocdsel2](https://user-images.githubusercontent.com/12570148/53703728-4ff77a00-3de3-11e9-9143-ac0f9e830f4a.png)

p.s. a cd cover image-pack will be available soon, keep an eye on the fba-forums :)

**Comment by dinkc64** [comment]
Also that error will happen if your cd images are not mode 1/2352.  We support mode1 2352 .cue/.bin and clonecd-style rips.  (Trurip style).
If you have redump or iso+wav style cd images, you can easily convert them with a simple program, details here: http://neo-source.com/index.php?topic=2487.msg26465#msg26465

**Comment by LodanZark** [comment]
Thank you very much that solved my issue ;)

**Comment by dinkc64** [comment]
you're welcome :)
