### ISSUE TITLE
NAM 1975 NO SOUND

### ISSUE THREAD

**Issue by OBurgerGuy** [barry65536/FBAlpha#25]
running lr-fba v0.2.97.44 cfbe1e1 with matching romset, under retroarch v1.7.6 running retropie v4.4.8: neo-geo nam 1975 produces no sound after coin inserted and game starts... prior to coin insertion there is attract sound.

**Comment by barbudreadmon** [comment]
1. you should post lr-fba issues into the right repo at https://github.com/libretro/fbalpha
2. before posting an issue, update to the latest commit, don't post issues about a version from november
3. aren't you that guy who used high values for cpu overclock and non-standard bios settings ? if so that's **important informations** to provide

**Comment by OBurgerGuy** [comment]
last version lr-fba depreciated, thought this was the place to post... got lost, thought i was on the last commit, not using any modifiers

**Comment by OBurgerGuy** [comment]
my apologies...

**Comment by barbudreadmon** [comment]
> my apologies...

Does that mean your issue disappeared after you updated to the latest commit ?
Sorry if i sounded rude, i just kinda remembered your name and the big troubles i had to reproduce your (similar ?) issue in the past, iirc those were triggered by your settings (something like using USA bios and an overclock setting of 200, which you didn't mention at first that time).
FYI i can't reproduce your issue on my side, i'm using default settings though.

**Comment by OBurgerGuy** [comment]
have followed your example, tested with my "usual" settings and without, unibios and stock bios... no, nothing has changed still no sound... this game seems to be the litmus test

**Comment by OBurgerGuy** [comment]
tghru many trials and errors with testing every game in cabinet, found that emulated cpu OC should be no more than 170, and all games work properly

**Comment by OBurgerGuy** [comment]
am on 2def8e5 now, still same results

**Comment by OBurgerGuy** [comment]
and yes deleted game config file every time i tested game
