### ISSUE TITLE
pFBA 3.4 - gaiapolis (gaiapols.zip) still causing switch to crash

### ISSUE THREAD

**Issue by Winklepicker** [barry65536/FBAlpha#29]
I'm afraid the game "gaiapolis (ver EAF)" (gaiapols.zip) and its clones, are still causing the switch to crash.

I'm using "SX OS 2.6.1" and firmware 7.0.1

**Comment by barbudreadmon** [comment]
Well, this is not the pFBA repository, and since gaiapolis is working fine in fbalpha, you'll have to ask the pFBA dev.
You could also use retroarch + the fbalpha core, supposedly it is working fine.

**Comment by Winklepicker** [comment]
sorry, I must have posted in wrong section. my mistake
