### ISSUE TITLE
Missing boardROM midssio

### ISSUE THREAD

**Issue by barbudreadmon** [barry65536/FBAlpha#31]
The new mcr drivers mention "midssio" & "ssio" as rom boards, which i think is the one declared at https://github.com/barry65536/FBAlpha/blob/c5ba574585f6f673341987524c5a676216a0729f/src/burn/drv/pre90s/d_mcr.cpp#L1617-L1626

However the name of the romdesc doesn't match (the content does match with the mame rom), and the rom isn't fully declared either

I tried fixing this stuff at https://pastebin.com/Six6RkL3 but didn't commit it since i wasn't sure it was the right way to fix this.

**Comment by dinkc64** [comment]
Thanks :)  fix will be in soon
