### ISSUE TITLE
(libretro) C++11 involved in atarile device

### ISSUE THREAD

**Issue by barbudreadmon** [barry65536/FBAlpha#4]
I know it might be too soon to build the atari drivers but i gave it a shot.

Building for apple based devices is failing on this line : 

https://github.com/barry65536/FBAlpha/blob/f3f1f31565c478a1a841074d8b70a5026b090536/src/burn/devices/atarirle.cpp#L314

osx : http://p.0bl.net/67472
ios : http://p.0bl.net/67473

It's saying `error: expected expression`, i tried googling this error but didn't find anything interesting

Edit : ok, actually it's complaining when building for other device too (not failing though), this code seems to be c++11 only : `src/burn/devices/atarirle.cpp:314:56: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11`

**Comment by barbudreadmon** [comment]
> 	mo->cliprect.nMinx      = 0;
	mo->cliprect.nMaxx      = nScreenWidth;
	mo->cliprect.nMiny      = 0;
	mo->cliprect.nMaxy      = nScreenHeight;

Btw, this code seems to solve the issue

**Comment by dinkc64** [comment]
it's funny, that code borked on iq_132's side the other day, and I forgot to change it.  oops:)
