### ISSUE TITLE
Sega G80v Games - Wrong colors

### ISSUE THREAD

**Issue by arnoldsecret** [barry65536/FBAlpha#9]
tacscan
FBA
![tacscan-181226-094316](https://user-images.githubusercontent.com/41223243/50428466-f65e6500-08f2-11e9-84aa-21a6be9a7667.png)
MAME
![tacscan](https://user-images.githubusercontent.com/41223243/50428508-3c1b2d80-08f3-11e9-8d96-59950936cdc7.png)

spacfury
FBA
![spacfury-181226-094631](https://user-images.githubusercontent.com/41223243/50428504-36254c80-08f3-11e9-9f3e-e686a1864bc1.png)
MAME
![spacfury](https://user-images.githubusercontent.com/41223243/50428516-4806ef80-08f3-11e9-8b3d-4381bced3ccb.png)

**Comment by dinkc64** [comment]
Hi Arnoldsecret,
thanks for the bug report - does the problem go away if you set your screen/video mode to 32 bit?

**Comment by barbudreadmon** [comment]
@dinkc64 i think he is using lr-fbalpha, and i didn't implement a feature to switch color mode (i thought every game was working with 16 bit). I'll take a look at this stuff.

**Comment by dinkc64** [comment]
the fix is in, thanks again for the bug report arnoldsecret.

best regards,
- dink
